### ISSUE TITLE
Relevant punctuation tokens missing in the vocabulary (IMHO) 

### ISSUE THREAD

**Issue by aitor-garcia-p** [dccuchile/beto#11]
Hello there,

First of all, congratulations and thank you very much for this fantastic work!

I have been using BETO in some projects, with no problem so far. It's tokenization and resulting subwords are, for Spanish, way better than the ones from multilingual BERT.

But suddenly I have noticed that I was hitting way too many UNK tokens (it usually happens when there is some weird character).
After checking BETO vocabulary (both cased and uncased) I have seen that it is missing characters like **%** (percent)   **/** (slash)   or  **;** (semicolon)   (and probably some other common punctuation marks and symbols).

Is it true that they are missing, or have I overlooked something?
I think that such characters (tokens) bear relevant information, and that fusing all of them into a UNK token may hurt the performance of the model.

As a quick fix, I have added them to my own customised version of the BETO vocabulary using some of the unused token positions.

It would be great if you could add those missing characters/symbols to the official BETO vocabulary, also for the version uploaded to the HuggingFace Transformers models directory, even if they were not pretrained with the model. This way they would be there for everybody and they would have their own embedding for fine-tuning tasks.

Thank you very much for your attention.

**Comment by josecannete** [comment]
Hello @aitor-garcia-p,

Thank you so much for your interest on the project and sorry for the late response.

You are right about those tokens, and they (among others) are now added to the vocabulary of both models. Please let me now if you find another token you think should be added.

Regards
