### ISSUE TITLE
Qué cambios se hicieron en el último release del modelo?

### ISSUE THREAD

**Issue by alexvaca0** [dccuchile/beto#18]
Buenas tardes. En primer lugar, muchas gracias por el esfuerzo de entrenar un modelo de lenguaje en español, además funciona muy bien, por lo que doblemente gracias. Llevo usando vuestro modelo mucho tiempo, y he notado que desde el release de Marzo funciona bastante mejor, saca muy buenos resultados. Me gustaría saber, si fuera posible, qué cambios hicieron en el modelo en este release. En cuanto a arquitectura vi que no ha cambiado nada, y el tokenizador parece el mismo. ¿Entrenaron más el modelo? ¿Lo entrenaron con un corpus diferente? Muchas gracias de antemano y gracias de nuevo por el esfuerzo realizado.

**Comment by josecannete** [comment]
Hola @alexvaca0, espero que te encuentres muy bien y muchas gracias por el interés en el proyecto.

En los siguientes links puedes revisar el diff con los cambios: [uncased](https://huggingface.co/dccuchile/bert-base-spanish-wwm-uncased/commit/27c33d23ff719992432504fc690144d9334ecca3) y [cased](https://huggingface.co/dccuchile/bert-base-spanish-wwm-cased/commit/48e731378cc28054067595b3ab83bbe9b94febde).

En definitiva los cambios principales son:
- Se agregó nuevos tokens (referente a puntuación) al vocabulario de los modelos.
- Se agregaron los tokenizer fast de la librería Transformers ([referencia](https://huggingface.co/transformers/main_classes/tokenizer.html#pretrainedtokenizerfast)).
- Se agregaron checkpoints de Tensorflow (antes solo estaba el de PyTorch).
- Se actualizaron algunas configuraciones para ajustarse a la última versión de ese momento de la librería Transformers.

No hubo más pretraining y de hecho los nuevos tokens agregados al vocabulario no están entrenados como tal, pero sí podrían verse beneficiados al momento de hacer fine-tuning.

Saludos!
