### ISSUE TITLE
Uso de Beto

### ISSUE THREAD

**Issue by Hernan4444** [dccuchile/beto#2]
¡Hola!

¿Es posible indicar cómo sería el proceso de utilizar Beto?, si bien sé que se debe utilizar la función `import_meta_graph`, no queda claro el formato del _input_ para poder correr el modelo y obtener el vector. Por ejemplo, si tengo la frase: "quiero ir a ese banco" ¿cómo llego a obtener el vector de dicha frase? ¿hay que hacer un preprocesamiento a esa frase o se entrega tal cual viene?

Saludos :v:

**Comment by josecannete** [comment]
Hola @Hernan4444 

Te recomiendo mirar primero la librería Transformers de HuggingFace, el repo es el siguiente: https://github.com/huggingface/transformers.

La documentación es muy completa también, el Quickstart debería resolver tus dudas: https://huggingface.co/transformers/quickstart.html

Saludos!
