### ISSUE TITLE
Pedida de opinión en el uso de BETO

### ISSUE THREAD

**Issue by lfalvarez** [dccuchile/beto#20]
Hola! Escribo para pedir una opinión respecto del uso de BETO.
Se las adelanto, hace sentido un fine tuninng en este contexto?

El contexto
--
 Estoy construyendo un sistema recomendador de propuestas ciudadanas. El asunto es que tengo una base de datos de unas 700 propuestas escritas por ciudadanos durante las elecciones del 2017, [estás propuestas](https://docs.google.com/spreadsheets/d/1QD-LS2NWJrQ1fmLtHHxf1ghTpImO3dihFo4zerIGLT8/edit#gid=1412100513) tienen un título y una descripción, las cuales vectorizo usando BETO y construyo un sistema para recuperar las propuestas más cercanas.
Saludos y muchas gracias por esto.

**Comment by sasu08** [comment]
Hola! En mi opinión, casi siempre es necesario un fine-tuning porque tomás de base el modelo pre-entrenado de BETO y lo ajustás a tu necesidad.
Recordá que BETO es un modelo de red neuronal multipropósito.

**Comment by lfalvarez** [comment]
Muchas gracias por tu respuesta.
