### ISSUE TITLE
BETO model size

### ISSUE THREAD

**Issue by asier-gutierrez** [dccuchile/beto#21]
Hi,

We released our [RoBERTa-base](https://huggingface.co/BSC-TeMU/roberta-base-bne) and [RoBERTa-large](https://huggingface.co/BSC-TeMU/roberta-large-bne) models recently and we compared them against your BETO. The paper states the following:

>  Our model has 12 self-attention layers with 16 attention-heads each (Vaswani et al., 2017), using 1024 as hidden size. In total our model has 110M parameters.

However, the configuration files ([BETO cased](https://huggingface.co/dccuchile/bert-base-spanish-wwm-cased/blob/main/config.json) and [BETO uncased](https://huggingface.co/dccuchile/bert-base-spanish-wwm-uncased/blob/main/config.json)) of the models uploaded to the HuggingFace Hub do not have the hyperparameters mentioned. They are 768 of hidden size instead of 1024 and 12 attention heads instead of 16. Otherwise the number of parameters (110M) does not fit.

**Comment by josecannete** [comment]
Hello @asier-gutierrez,

You are right, the correct ones are those in the configuration files. Thank you for point it out, we'll fix it in an updated version of the paper.

Thanks!

**Comment by josecannete** [comment]
It is updated now.

Thank you!
