### ISSUE TITLE
AutoModel bug (super easy fix)

### ISSUE THREAD

**Issue by leinaxd** [dccuchile/beto#27]
**Issue**:
   HuggingFace AutoModel / AutoTokenizer doesn't detect the model per se.

**Fix:**
Would be possible to update the config.json to append the following **first line** for both **cased**/**uncased**:

```
{
  "model_type": "bert",
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
   ...
}
```

Thx in advance

=============================
Example Before:
```
from transformers import BertTokenizer
BertTokenizer.from_pretrained( path )
```
Example Now:
```
from transformers import AutoTokenizer
AutoTokenizer.from_pretrained( path ) #BertTokenizer still works
```

==============================
This is important in order to Automatize the model selection. (Getting the scores from multiple models i.e. BETO, RoBERTa, GPT-2)

**Comment by josecannete** [comment]
Hi! Sorry for the late response and thanks for reporting.

The configs in the HuggingFace Hub are already updated to support that feature: https://huggingface.co/dccuchile/bert-base-spanish-wwm-uncased.

I'm closing for now.
