### ISSUE TITLE
Missing hyperparameters for fine-tuning

### ISSUE THREAD

**Issue by alexvaca0** [dccuchile/beto#5]
Hi there; first of all thank you very much for developing a spanish bert model, the community was waiting for this and we really appreciate it. It would be very helpful if you published the hyperparameters you've used to get the results shown in the README.md. Is there any paper you've published on the subject / blog where you described the strategy followed to train the model?
Thank you very much in advance :)

**Comment by gchaperon** [comment]
Hi, we appreciate your interest.

No paper yet.

I finetuned the model for the conll2002 and the MLDoc task, and I just linked the respective results to the experiments I performed. There is (spaghetti) code in the linked repo as well.

About the strategy, I tried to follow as close as possible the methodology described in [[2]](https://arxiv.org/pdf/1904.09077.pdf).

**Comment by josecannete** [comment]
Hello, thanks again for your interest.

We are working on fine-tune BETO in more tasks and preparing all to publish code/hyperparameters.

For now you can find some in @gchaperon repo and also some here: https://github.com/josecannete/beto-benchmarking

If you have any doubts feel free to ask :)
