### ISSUE TITLE
Code for running benchmark

### ISSUE THREAD

**Issue by mananeau** [dccuchile/beto#6]
Muchisimas gracias para la contribución :) 

I am currently pre-training BERT for another language and am hoping to benchmark my model against mBERT just like you did on tasks such as POS in other languages than English. Do you have any resources you could share (code, repos, etc..) and that I could use to do this benchmark?

**Comment by gchaperon** [comment]
Hi! Thanks for your interest :)

Sure! I was responsible for finetuning for the conll2002 task and the MLDoc dataset. My scripts can be found [here](https://github.com/gchaperon/beto-benchmarks). This is very much a WIP so my code is quite messy.

Also, I based my scripts of off the amazing work from :hugs: , so my scripts are similar to their [examples](https://huggingface.co/transformers/examples.html).

**Comment by mananeau** [comment]
Thanks a lot for your reply :)
