### ISSUE TITLE
Gestionar [UNK]

### ISSUE THREAD

**Issue by Javier-Jimenez99** [dccuchile/beto#9]
He diseñado un modelo Bert para resolver NER basado en su modelo, pero me gustaría saber como revertir los valores que tienen los tokens de `[UNK]`. Es decir obtener el valor real que tiene en la frase el token que contiene esta etiqueta. 

Esto se debe a que a veces se detectan  entidades a las que se les asigna esta etiqueta y no puedo saber de cuál es su nombre.

**Comment by josecannete** [comment]
Hola @Javier-Jimenez99,

Puedes encontrar información al respecto en [la librería Transformers](https://github.com/huggingface/transformers).

Saludos!
